#!/bin/bash

get_qt_size() {
    du -sh "${QT5_BASE_DIR}"
}

if [ -r "$QT5_BASE_DIR/bin/qmake.exe" ]; then
    echo "Qt5 already installed; Qt installation size: $(get_qt_size)"
    exit 0
fi

wget --quiet http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
if ! ./qt-unified-windows-x86-online.exe --verbose --script ${TRAVIS_BUILD_DIR}/support/qt-installer-windows.qs; then
    exit 1;
fi
rm -rf qt-unified-windows-x86-online.exe
echo "Qt installation size (before removing docs and examples): $(get_qt_size)"
rm -rf C:/Qt/Docs C:/Q/Examples C:/Qt/Tools/QtCreator C:/Qt/vcredist C:/Qt/MaintenanceTool*

echo "Qt installation size: $(get_qt_size)"

