#!/bin/bash

# conditions checking
export GITHUB_DRAFT_RELEASE=0
export GITHUB_PRERELEASE=1

if [ "$TRAVIS_BRANCH" != master ]; then
    if grep -q '#draft_release' <<<"$TRAVIS_COMMIT_MESSAGE"; then
        GITHUB_DRAFT_RELEASE=1
    else
        echo "Not on master, and no #draft_release specified. Skipping deploy."
        exit 0
    fi
fi

python3 -m venv ${TRAVIS_BUILD_DIR}/build/venv
source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
pip3 install wheel
pip3 install PyGithub
cd "${TRAVIS_BUILD_DIR}/build"
wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/58ecc34c4171b9c135d93a4bf03bde3ebea3bf7f/python/travis_release.py" -O "${TRAVIS_BUILD_DIR}/travis_release.py"
python3 "${TRAVIS_BUILD_DIR}/build/travis_release.py" "$@"

