#!/bin/bash
PYTHON_BINARY=python3
if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    PYTHON_BINARY=python
fi

# conditions checking
export GITHUB_DRAFT_RELEASE=0
export GITHUB_PRERELEASE=1

if [ "$TRAVIS_BRANCH" != master ]; then
    if grep -q '#draft_release' <<<"$TRAVIS_COMMIT_MESSAGE"; then
        GITHUB_DRAFT_RELEASE=1
    else
        echo "Not on master, and no #draft_release specified. Skipping deploy."
        exit 0
    fi
fi

$PYTHON_BINARY -m venv ${TRAVIS_BUILD_DIR}/build/venv
source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
pip3 install wheel
pip3 install PyGithub
cd "${TRAVIS_BUILD_DIR}/build"
wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/d5ff2ce5b17d7561a8f729cddd2bdf8b6d5eb556/python/travis_release.py" -O "${TRAVIS_BUILD_DIR}/build/travis_release.py"
$PYTHON_BINARY "${TRAVIS_BUILD_DIR}/build/travis_release.py" "$@"

