if: '(branch = master OR type = pull_request OR commit_message =~ /.*#trigger_ci.*/) AND (NOT commit_message =~ /.*#skip_ci.*/) AND ( tag IS blank )'
matrix:
    include:
        - language: cpp
          env:
            - QT5_BASEDIR: "C:/Qt"
            - QT5_DIR: "C:/Qt/${QT5_VERSION}/msvc2017_64"
            - PATH: /c/Python38:/c/Python38/Scripts:$PATH
          name: AstroPhoto Plus Desktop - Windows
          if: 'NOT commit_message =~ /.*#skip_windows.*/'
          os: windows
          before_install:
            - cinst -y python3 7zip
            - pip install requests
          install:
            - python ${TRAVIS_BUILD_DIR}/support/qt-installer.py "$QT5_BASEDIR"
          before_script:
            - mkdir ${TRAVIS_BUILD_DIR}/build
            - export PATH="$QT5_DIR/bin:$PATH"
          script:
            - cd ${TRAVIS_BUILD_DIR}/build
            - if ! cmake ${TRAVIS_BUILD_DIR} -DCMAKE_PREFIX_PATH=${QT5_DIR} -DQt5_DIR=${QT5_DIR} -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=$PWD/pkg; then
                  cat ${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log;
                  exit 1;
              fi
            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release 
          before_deploy:
            - export TRAVIS_WINDOWS_BUILD_DIR="$( cd "${TRAVIS_BUILD_DIR}"; pwd -W)"
            - cd ${TRAVIS_BUILD_DIR}/build
            - cinst -y nsis
            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release --target install
            - $QT5_DIR/bin/windeployqt --dir $TRAVIS_BUILD_DIR/build/pkg/bin $TRAVIS_BUILD_DIR/build/pkg/bin/AstroPhotoPlus-Desktop.exe  --release --no-compiler-runtime
            - cd "$TRAVIS_BUILD_DIR/build/pkg/bin"
            - |
                "C:/Program Files (x86)/NSIS/makensis.exe" //NOCD ${TRAVIS_BUILD_DIR}/src/resources/installer.nsis
            - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
            - export VERSION=${PROJECT_VERSION}
            - mv -v "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Setup.exe" "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
          deploy:
            skip_cleanup: true
            provider: script
            script: bash "${TRAVIS_BUILD_DIR}/support/travis_deploy" "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
            on:
              all_branches: true
              tags: false

        - language: cpp
          name: Astrophoto Plus Desktop - Linux AppImage
          if: 'NOT commit_message =~ /.*#skip_linux.*/'
          dist: xenial
          os: linux
          env:
              - QT5_BASEDIR: "$HOME/Qt"
              - QT5_DIR: "$HOME/Qt/${QT5_VERSION}/gcc_64"
          before_install:
              - sudo apt-get update -qq
              - sudo apt-get -qq -y install libgl1-mesa-dev wget libfontconfig1 libxrender1  libdbus-1-3 libxkbcommon0 libxkbcommon-x11-0 xvfb libpulse-dev p7zip-full python3-requests gstreamer1.0-plugins-base
              - sudo apt-get -qq -y install libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-present0 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcb1
          install:
              - python3 ${TRAVIS_BUILD_DIR}/support/qt-installer.py "$QT5_BASEDIR"
          before_script:
              - mkdir ${TRAVIS_BUILD_DIR}/build
              - cd ${TRAVIS_BUILD_DIR}/build
          script:
              - cd ${TRAVIS_BUILD_DIR}/build
              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${QT5_DIR} -DQt5_DIR=${QT5_DIR}
              - make -j$(nproc)
              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
              - ls -alh ${TRAVIS_BUILD_DIR}/build/src
          before_deploy:
              - cd "${TRAVIS_BUILD_DIR}/build"
              - wget --quiet https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
              - chmod a+x linuxdeployqt*.AppImage
              - export VERSION=${PROJECT_VERSION}
              - ${TRAVIS_BUILD_DIR}/build/linuxdeployqt*.AppImage appdir/usr/share/applications/*.desktop -appimage -qmake="${QT5_DIR}/bin/qmake" -verbose=2
              - sudo apt-get install python3 python3-venv
              - mv -v "${TRAVIS_BUILD_DIR}/build"/AstroPhoto*AppImage* "${TRAVIS_BUILD_DIR}/build/AstroPhoto-Plus-Desktop-Linux.AppImage"
          deploy:
            skip_cleanup: true
            provider: script
            script: bash "${TRAVIS_BUILD_DIR}/support/travis_deploy" "${TRAVIS_BUILD_DIR}/build/AstroPhoto-Plus-Desktop-Linux.AppImage"
            on:
              all_branches: true
              tags: false

        - language: cpp
          name: Astrophoto Plus Desktop - Mac Os App
          if: 'NOT commit_message =~ /.*#skip_osx.*/'
          os: osx
          env:
              - QT5_BASEDIR: "$HOME/Qt"
              - QT5_DIR: "$HOME/Qt/${QT5_VERSION}/clang_64"
          before_install:
              - brew install p7zip
              - pip3 install requests
          install:
              - python3 ${TRAVIS_BUILD_DIR}/support/qt-installer.py "$QT5_BASEDIR"
          before_script:
              - mkdir ${TRAVIS_BUILD_DIR}/build
              - cd ${TRAVIS_BUILD_DIR}/build
          script:
              - cd ${TRAVIS_BUILD_DIR}/build
              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${QT5_DIR} -DQt5_DIR=${QT5_DIR}
#              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=${QT5_DIR}/lib/cmake/Qt5/
              - make -j$(nproc)
              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
          before_deploy:
              - cd "${TRAVIS_BUILD_DIR}/build"
              - echo ${PROJECT_VERSION}
              - export VERSION=${PROJECT_VERSION}
              - ${QT5_DIR}/bin/macdeployqt appdir/AstroPhotoPlus-Desktop.app -verbose=2
              - ln -s /Applications ${TRAVIS_BUILD_DIR}/build/appdir
              - hdiutil create -volname "AstroPhoto Plus" -srcfolder "${TRAVIS_BUILD_DIR}/build/appdir" -ov -format UDZO "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
          deploy:
            skip_cleanup: true
            provider: script
            script: bash "${TRAVIS_BUILD_DIR}/support/travis_deploy" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
            on:
              all_branches: true
              tags: false

