if: '(branch = master OR type = pull_request OR commit_message =~ /.*#trigger_ci.*/) AND (NOT commit_message =~ /.*#skip_ci.*/) AND ( tag IS blank )'
matrix:
    include:
        - language: cpp
          env:
            - QT5_BASE_DIR: C:/Qt/5.12.5/msvc2017_64
            - PATH: /c/Python38:/c/Python38/Scripts:$PATH
          name: AstroPhoto Plus Desktop - Windows
          os: windows
          cache:
            directories:
            - C:/Qt
          install:
            - bash ${TRAVIS_BUILD_DIR}/support/travis-install-qt-for-windows
          before_script:
            - mkdir ${TRAVIS_BUILD_DIR}/build
            - $QT5_BASE_DIR/bin/qtenv2.bat
          script:
            - cd ${TRAVIS_BUILD_DIR}/build
            - if ! cmake ${TRAVIS_BUILD_DIR} -DCMAKE_PREFIX_PATH=${QT5_BASE_DIR} -DQt5_DIR=${QT5_BASE_DIR} -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=$PWD/pkg; then
                  cat ${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log;
                  exit 1;
              fi
            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release 
          before_deploy:
            - export TRAVIS_WINDOWS_BUILD_DIR="$( cd "${TRAVIS_BUILD_DIR}"; pwd -W)"
            - cd ${TRAVIS_BUILD_DIR}/build
            - cinst -y python3
            - cinst -y nsis
            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release --target install
            - $QT5_BASE_DIR/bin/windeployqt --dir $TRAVIS_BUILD_DIR/build/pkg/bin $TRAVIS_BUILD_DIR/build/pkg/bin/AstroPhotoPlus-Desktop.exe  --release --no-compiler-runtime
            - cd "$TRAVIS_BUILD_DIR/build/pkg/bin"
            - |
                "C:/Program Files (x86)/NSIS/makensis.exe" //NOCD ${TRAVIS_BUILD_DIR}/src/resources/installer.nsis
            - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
            - echo ${PROJECT_VERSION}
            - echo ${TRAVIS_WINDOWS_BUILD_DIR}
            - export VERSION=${PROJECT_VERSION}
            - cd ${TRAVIS_BUILD_DIR}/build
            - pwd
            - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
            - ls -alh ${TRAVIS_BUILD_DIR}/build/travis_release.py
            - md5sum travis_release.py
            - pip install PyGithub

          deploy:
            skip_cleanup: true
            provider: script
            script: python ${TRAVIS_WINDOWS_BUILD_DIR}/build/travis_release.py "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Setup.exe"
            on:
              branch:
                - master
              tags: false


        - language: cpp
          name: Astrophoto Plus Desktop - Linux AppImage
          dist: xenial
          os: linux
          before_install:
              - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
              - sudo apt-get update -qq
          install:
              - sudo apt-get -y install libgl1-mesa-dev qt512base qt512multimedia qt512webengine
          before_script:
              - mkdir ${TRAVIS_BUILD_DIR}/build
              - cd ${TRAVIS_BUILD_DIR}/build
          script:
              - source /opt/qt*/bin/qt*-env.sh
              - cd ${TRAVIS_BUILD_DIR}/build
              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
              - make -j$(nproc)
              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
              - ls -alh ${TRAVIS_BUILD_DIR}/build/src
          before_deploy:
              - cd "${TRAVIS_BUILD_DIR}/build"
              - wget --quiet https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
              - wget --quiet https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
              - chmod a+x linuxdeployqt*.AppImage
              - chmod a+x appimagetool*.AppImage
              - echo ${PROJECT_VERSION}
              - export VERSION=${PROJECT_VERSION}
              - ${TRAVIS_BUILD_DIR}/build/linuxdeployqt*.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
              - cp -av /usr/lib/x86_64-linux-gnu/nss/* appdir/usr/lib/
              - ${TRAVIS_BUILD_DIR}/build/appimagetool*.AppImage appdir
              - sudo apt-get install python3 python3-venv
              - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
              - ls -alh ${TRAVIS_BUILD_DIR}/build
              - md5sum travis_release.py
              - python3 -m venv ${TRAVIS_BUILD_DIR}/build/venv
              - source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
              - pip3 install PyGithub
          deploy:
            skip_cleanup: true
            provider: script
            script: python3 "${TRAVIS_BUILD_DIR}/build/travis_release.py" "${TRAVIS_BUILD_DIR}/build"/AstroPhoto*AppImage*
            on:
              branch:
                - master
              tags: false

        - language: cpp
          name: Astrophoto Plus Desktop - Mac Os App
          os: osx
          install:
              - brew install qt5
              -export QT5_BREW_PATH="$( ls -d /usr/local/Cellar/qt/* | head -n 1)"
          before_script:
              - mkdir ${TRAVIS_BUILD_DIR}/build
              - cd ${TRAVIS_BUILD_DIR}/build
          script:
              - cd ${TRAVIS_BUILD_DIR}/build
              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=${QT5_BREW_PATH}/lib/cmake/Qt5/
              - make -j$(nproc)
              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
          before_deploy:
              - cd "${TRAVIS_BUILD_DIR}/build"
              - echo ${PROJECT_VERSION}
              - export VERSION=${PROJECT_VERSION}
              - ${QT5_BREW_PATH}/bin/macdeployqt appdir/AstroPhotoPlus-Desktop.app -dmg
              - brew install python3 
              - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
              - ls -alh ${TRAVIS_BUILD_DIR}/build
              - md5sum travis_release.py
              - python3 -m venv ${TRAVIS_BUILD_DIR}/build/venv
              - source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
              - pip3 install PyGithub
          deploy:
            skip_cleanup: true
            provider: script
            script: python3 "${TRAVIS_BUILD_DIR}/build/travis_release.py" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop.dmg"
            on:
              branch:
                - master
              tags: false

