#!/bin/bash
set -e
set -x
wget "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/dcbf738b7d50b8987c9fd2d8c0ac652f072ab278/python/travis_release.py"
ls -alh ${TRAVIS_BUILD_DIR}/build
md5sum travis_release.py
source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
python3 -v ${TRAVIS_BUILD_DIR}/build/travis_release.py ${TRAVIS_BUILD_DIR}/build/AstroPhoto*AppImage*


