execute_process(COMMAND git rev-parse --short HEAD OUTPUT_VARIABLE COMMIT_ID WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
string(STRIP ${COMMIT_ID} COMMIT_ID)
execute_process(COMMAND git show -s --format=%ci ${COMMIT_ID} OUTPUT_VARIABLE COMMIT_DATE WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
string(REPLACE "-" "" COMMIT_DATE ${COMMIT_DATE})
string(SUBSTRING ${COMMIT_DATE} 0 8 COMMIT_DATE)
set(PROJECT_VERSION_SUFFIX _${COMMIT_DATE}-${COMMIT_ID})

